#include "01_introduction.typ"
#include "02_math_background.typ"
#include "03_methodology.typ"
#include "04_experiments.typ"
#include "05_discussion.typ"
#include "06_proposed_system.typ"
#include "07_conclusion.typ"
